#------------------------------
# Configuration du site

title: b-event
language: "fr"
baseurl: ""
source: ""
url: ""
description: Un site web (Agenda) pour répertorier toutes les activités de la ville.
keywords: ["unsta", "Jekyll"]


#---------------------
# A propos de l'auteur
author: flavien-hugs
email: unsta@pm.me


#--------------------------
# Google Analytics
google-analytics: # ajout de l'identifiant du site



#-------------------
# configuration du build
debug: false
safe: true
markdown: kramdown
kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false
permalink: '/agenda/:title'
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag

paginate: 7
paginate_path: "/page/:num"

include:
    - _pages

includes_dir : _includes
layouts_dir : _layouts

sass:
    sass_dir: _sass
    style: compressed

timezone: Africa/Nairobi
highlighter: rouge
sitemap: true
feed:
    path: atom.xml

livereload: true

#-----------------------------
# Site owner configuration
owner:
    name: unsta
    author: flavien-hugs
    email: unsta@pm.me
